server:
    port: 8686
    servlet:
        contextPath: /spring-boot-five         
---
spring:
    profiles: club
server:
    port: 8686
    servlet:
        contextPath: /spring-boot-five 
---

spring:
    profiles: player
server:
    port: 8888
    servlet:
        contextPath: /spring-boot-five-player 